### ISSUE TITLE
Usage of typedoc-plugin-extras

### ISSUE THREAD

**Issue by Drarig29** [TreeFarmer/embed-table#1]
Hi! I see you are using my TypeDoc plugin!

I want to make sure you know that, as you use it, the plugin doesn't do anything: all options are now opt-in and you are not opting for any option.

Check this section of the README for more details: https://github.com/Drarig29/typedoc-plugin-extras#arguments

**Comment by Fyrlex** [comment]
Hi there! I was taking a look at it the other day to be able to use a favicon. But I was having difficulty setting that up and left it for now. Also, I cannot figure out how to ignore certain files when compiling the docs which is where I want to have my favicon stored. 

Thank you for reaching out and I hope to be able to get it setup soon!
Fyrlex

**Comment by Drarig29** [comment]
Okay, I see 😁
