### ISSUE TITLE
Package installation requires tsc to be installed globally

### ISSUE THREAD

**Issue by Touratica** [TreeFarmer/embed-table#5]
When I was trying to install v4.0.5 (was using v3.0.0), the command failed with the error `sh: 1: tsc: not found`. Through this error, I made the assumption I had to had typescript installed globally and, sure enough, once I did install it with `npm i -g typescript`, installation went without further issues.

**Comment by Touratica** [comment]
The issue was indeed solved but it appears to have resurfaced.

**Comment by idkroff** [comment]
Still needs a tsc to be preinstalled
