### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by ExtremeStylez** [TreeFarmer/embed-table#8]
This happens when i try `npm i embed-table`

One is replit and the other is another host:

![Screenshot_20221130-043707-1](https://user-images.githubusercontent.com/46006826/204694696-d60488e2-f7cf-4166-9bbf-42c06fc2b6db.jpg)
![Screenshot_20221130-043740-1](https://user-images.githubusercontent.com/46006826/204694701-1e27c54b-83d3-4255-a1f5-e6f31f313868.jpg)

**Comment by Fyrlex** [comment]
Hey! Thanks for reporting this error. It will be fixed in #7 when the pull request is accepted.

**Comment by Fyrlex** [comment]
Closed with #7
